spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: ${KEYCLOACK_CLIENT_ID}
            clientSecret: ${KEYCLOACK_SECRET}
            scope: openid,email,profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          keycloak-client-credentials:
            clientId: ${KEYCLOACK_CLIENT_ID}
            clientSecret: ${KEYCLOACK_SECRET}
            scope: openid,email,profile
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOACK_BASE}/realms/${KEYCLOACK_REALM}
            user-name-attribute: preferred_username
          keycloak-client-credentials:
            issuer-uri: ${KEYCLOACK_BASE}/realms/${KEYCLOACK_REALM}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOACK_BASE}/realms/${KEYCLOACK_REALM}
          jwk-set-uri: ${KEYCLOACK_BASE}/realms/${KEYCLOACK_REALM}/protocol/openid-connect/certs
